services:
  app:
    build:
      context: .
      dockerfile: ./build/user.Dockerfile
    depends_on: 
      pg_db:
        condition: service_healthy
    restart: always
    ports:
      - "8080:8080"

  pg_db: #host
    image: postgres
    container_name: userdb
    env_file:
      - .env 
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pguser -h pg_db"]
      interval: 5s
      timeout: 5s
      retries: 5    
      start_period: 1s

  migrate: 
    image: artsafin/goose-migrations
    container_name: user_migrate
    depends_on: 
      pg_db:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations
    entrypoint: ["goose", "postgres", "postgres://pguser:pass@pg_db:5432/userdb?sslmode=disable"]
    command: up

  # pgadmin:
  #   image: dpage/pgadmin4
  #   logging:
  #     driver: none
  #   container_name: pgadmin
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=user@domain.com
  #     - PGADMIN_DEFAULT_PASSWORD=SuperSecret
  #   ports:
  #     - "8081:80"